version: "2"
run:
  build-tags:
    - e2e
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - godox
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - mnd
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - tagliatelle
    - testpackage
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - gopkg.in/yaml.v3.Marshal
    errchkjson:
      check-error-free-encoding: true
      report-no-exported: true
    gocyclo:
      min-complexity: 15
    gomoddirectives:
      replace-local: true
    govet:
      enable:
        - shadow
    importas:
      alias:
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/client-go/dynamic/fake
          alias: dynamicfake
        - pkg: k8s.io/client-go/testing
          alias: clienttesting
      no-unaliased: true
      no-extra-aliases: true
    loggercheck:
      kitlog: false
      klog: true
      logr: false
      zap: true
      require-string-key: true
      no-printf-like: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: true
    revive:
      rules:
        - name: dot-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
        path: _test\.go
      - linters:
          - govet
        path: _test\.go
        text: 'shadow: declaration of "ctx" shadows declaration at line ([\d]+)'
      - linters:
          - govet
        path: .go
        text: 'shadow: declaration of "err" shadows declaration at line ([\d]+)'
      - linters:
          - importas
        text: has alias "" which is not part of config
      - path: (.+)\.go$
        text: Using the variable on range scope `tc` in function literal
      - path: (.+)\.go$
        text: Using the variable on range scope `tt` in function literal
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project/opentelemetry-collector-components)
        - blank
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/kyma-project/opentelemetry-collector-components
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
