# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2


changelog:
  use: github
  sort: asc
  groups:
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Dependencies
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Test suites
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Features
      order: 0
  filters:
    exclude:
        - '^.*?chore(\([[:word:]]+\))??!?:.+$'
        - '^(B|b)ump'

builds:
  -
    skip: true
