// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/istio_enrichment component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("istio_enrichment")
	ScopeName = "github.com/kyma-project/opentelemetry-collector-components/processor/istioenrichmentprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
