// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetK8sNamespaceName("k8s.namespace.name-val")
			rb.SetK8sResourceGroup("k8s.resource.group-val")
			rb.SetK8sResourceKind("k8s.resource.kind-val")
			rb.SetK8sResourceName("k8s.resource.name-val")
			rb.SetK8sResourceVersion("k8s.resource.version-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 5, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 5, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("k8s.namespace.name")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, "k8s.namespace.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("k8s.resource.group")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, "k8s.resource.group-val", val.Str())
			}
			val, ok = res.Attributes().Get("k8s.resource.kind")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, "k8s.resource.kind-val", val.Str())
			}
			val, ok = res.Attributes().Get("k8s.resource.name")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, "k8s.resource.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("k8s.resource.version")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, "k8s.resource.version-val", val.Str())
			}
		})
	}
}
