// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("kymastats")
	ScopeName = "github.com/kyma-project/opentelemetry-collector-components/receiver/kymastatsreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
