// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetK8sNamespaceName sets provided value as "k8s.namespace.name" attribute.
func (rb *ResourceBuilder) SetK8sNamespaceName(val string) {
	if rb.config.K8sNamespaceName.Enabled {
		rb.res.Attributes().PutStr("k8s.namespace.name", val)
	}
}

// SetK8sResourceGroup sets provided value as "k8s.resource.group" attribute.
func (rb *ResourceBuilder) SetK8sResourceGroup(val string) {
	if rb.config.K8sResourceGroup.Enabled {
		rb.res.Attributes().PutStr("k8s.resource.group", val)
	}
}

// SetK8sResourceKind sets provided value as "k8s.resource.kind" attribute.
func (rb *ResourceBuilder) SetK8sResourceKind(val string) {
	if rb.config.K8sResourceKind.Enabled {
		rb.res.Attributes().PutStr("k8s.resource.kind", val)
	}
}

// SetK8sResourceName sets provided value as "k8s.resource.name" attribute.
func (rb *ResourceBuilder) SetK8sResourceName(val string) {
	if rb.config.K8sResourceName.Enabled {
		rb.res.Attributes().PutStr("k8s.resource.name", val)
	}
}

// SetK8sResourceVersion sets provided value as "k8s.resource.version" attribute.
func (rb *ResourceBuilder) SetK8sResourceVersion(val string) {
	if rb.config.K8sResourceVersion.Enabled {
		rb.res.Attributes().PutStr("k8s.resource.version", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
