// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// KymaResourceStatusConditionsMetricAttributeKey specifies the key of an attribute for the kyma.resource.status.conditions metric.
type KymaResourceStatusConditionsMetricAttributeKey string

const (
	KymaResourceStatusConditionsMetricAttributeKeyGroup     KymaResourceStatusConditionsMetricAttributeKey = "group"
	KymaResourceStatusConditionsMetricAttributeKeyKind      KymaResourceStatusConditionsMetricAttributeKey = "kind"
	KymaResourceStatusConditionsMetricAttributeKeyName      KymaResourceStatusConditionsMetricAttributeKey = "name"
	KymaResourceStatusConditionsMetricAttributeKeyNamespace KymaResourceStatusConditionsMetricAttributeKey = "namespace"
	KymaResourceStatusConditionsMetricAttributeKeyReason    KymaResourceStatusConditionsMetricAttributeKey = "reason"
	KymaResourceStatusConditionsMetricAttributeKeyStatus    KymaResourceStatusConditionsMetricAttributeKey = "status"
	KymaResourceStatusConditionsMetricAttributeKeyType      KymaResourceStatusConditionsMetricAttributeKey = "type"
	KymaResourceStatusConditionsMetricAttributeKeyVersion   KymaResourceStatusConditionsMetricAttributeKey = "version"
)

// KymaResourceStatusConditionsMetricConfig provides config for the kyma.resource.status.conditions metric.
type KymaResourceStatusConditionsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []KymaResourceStatusConditionsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *KymaResourceStatusConditionsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *KymaResourceStatusConditionsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case KymaResourceStatusConditionsMetricAttributeKeyGroup, KymaResourceStatusConditionsMetricAttributeKeyKind, KymaResourceStatusConditionsMetricAttributeKeyName, KymaResourceStatusConditionsMetricAttributeKeyNamespace, KymaResourceStatusConditionsMetricAttributeKeyReason, KymaResourceStatusConditionsMetricAttributeKeyStatus, KymaResourceStatusConditionsMetricAttributeKeyType, KymaResourceStatusConditionsMetricAttributeKeyVersion:
		default:
			return fmt.Errorf("metric kyma.resource.status.conditions doesn't have an attribute %v, valid attributes: [group, kind, name, namespace, reason, status, type, version]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// KymaResourceStatusStateMetricAttributeKey specifies the key of an attribute for the kyma.resource.status.state metric.
type KymaResourceStatusStateMetricAttributeKey string

const (
	KymaResourceStatusStateMetricAttributeKeyGroup     KymaResourceStatusStateMetricAttributeKey = "group"
	KymaResourceStatusStateMetricAttributeKeyKind      KymaResourceStatusStateMetricAttributeKey = "kind"
	KymaResourceStatusStateMetricAttributeKeyName      KymaResourceStatusStateMetricAttributeKey = "name"
	KymaResourceStatusStateMetricAttributeKeyNamespace KymaResourceStatusStateMetricAttributeKey = "namespace"
	KymaResourceStatusStateMetricAttributeKeyState     KymaResourceStatusStateMetricAttributeKey = "state"
	KymaResourceStatusStateMetricAttributeKeyVersion   KymaResourceStatusStateMetricAttributeKey = "version"
)

// KymaResourceStatusStateMetricConfig provides config for the kyma.resource.status.state metric.
type KymaResourceStatusStateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []KymaResourceStatusStateMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *KymaResourceStatusStateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *KymaResourceStatusStateMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case KymaResourceStatusStateMetricAttributeKeyGroup, KymaResourceStatusStateMetricAttributeKeyKind, KymaResourceStatusStateMetricAttributeKeyName, KymaResourceStatusStateMetricAttributeKeyNamespace, KymaResourceStatusStateMetricAttributeKeyState, KymaResourceStatusStateMetricAttributeKeyVersion:
		default:
			return fmt.Errorf("metric kyma.resource.status.state doesn't have an attribute %v, valid attributes: [group, kind, name, namespace, state, version]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for kymastats metrics.
type MetricsConfig struct {
	KymaResourceStatusConditions KymaResourceStatusConditionsMetricConfig `mapstructure:"kyma.resource.status.conditions"`
	KymaResourceStatusState      KymaResourceStatusStateMetricConfig      `mapstructure:"kyma.resource.status.state"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		KymaResourceStatusConditions: KymaResourceStatusConditionsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []KymaResourceStatusConditionsMetricAttributeKey{KymaResourceStatusConditionsMetricAttributeKeyGroup, KymaResourceStatusConditionsMetricAttributeKeyKind, KymaResourceStatusConditionsMetricAttributeKeyName, KymaResourceStatusConditionsMetricAttributeKeyNamespace, KymaResourceStatusConditionsMetricAttributeKeyReason, KymaResourceStatusConditionsMetricAttributeKeyStatus, KymaResourceStatusConditionsMetricAttributeKeyType, KymaResourceStatusConditionsMetricAttributeKeyVersion},
		},
		KymaResourceStatusState: KymaResourceStatusStateMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []KymaResourceStatusStateMetricAttributeKey{KymaResourceStatusStateMetricAttributeKeyGroup, KymaResourceStatusStateMetricAttributeKeyKind, KymaResourceStatusStateMetricAttributeKeyName, KymaResourceStatusStateMetricAttributeKeyNamespace, KymaResourceStatusStateMetricAttributeKeyState, KymaResourceStatusStateMetricAttributeKeyVersion},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for kymastats resource attributes.
type ResourceAttributesConfig struct {
	K8sNamespaceName   ResourceAttributeConfig `mapstructure:"k8s.namespace.name"`
	K8sResourceGroup   ResourceAttributeConfig `mapstructure:"k8s.resource.group"`
	K8sResourceKind    ResourceAttributeConfig `mapstructure:"k8s.resource.kind"`
	K8sResourceName    ResourceAttributeConfig `mapstructure:"k8s.resource.name"`
	K8sResourceVersion ResourceAttributeConfig `mapstructure:"k8s.resource.version"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		K8sNamespaceName: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sResourceGroup: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sResourceKind: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sResourceName: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sResourceVersion: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for kymastats metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
