// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKymaResourceStatusConditionsDataPoint(ts, 1, "group-val", "kind-val", "name-val", "namespace-val", "reason-val", "status-val", "type-val", "version-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKymaResourceStatusStateDataPoint(ts, 1, "group-val", "kind-val", "name-val", "namespace-val", "state-val", "version-val")

			rb := mb.NewResourceBuilder()
			rb.SetK8sNamespaceName("k8s.namespace.name-val")
			rb.SetK8sResourceGroup("k8s.resource.group-val")
			rb.SetK8sResourceKind("k8s.resource.kind-val")
			rb.SetK8sResourceName("k8s.resource.name-val")
			rb.SetK8sResourceVersion("k8s.resource.version-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "kyma.resource.status.conditions":
					assert.False(t, validatedMetrics["kyma.resource.status.conditions"], "Found a duplicate in the metrics slice: kyma.resource.status.conditions")
					validatedMetrics["kyma.resource.status.conditions"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The resource status conditions. Possible metric values for condition status are 'True' => 1, 'False' => 0, and -1 for other status values.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					groupAttrVal, ok := dp.Attributes().Get("group")
					assert.True(t, ok)
					assert.Equal(t, "group-val", groupAttrVal.Str())
					kindAttrVal, ok := dp.Attributes().Get("kind")
					assert.True(t, ok)
					assert.Equal(t, "kind-val", kindAttrVal.Str())
					nameAttrVal, ok := dp.Attributes().Get("name")
					assert.True(t, ok)
					assert.Equal(t, "name-val", nameAttrVal.Str())
					namespaceAttrVal, ok := dp.Attributes().Get("namespace")
					assert.True(t, ok)
					assert.Equal(t, "namespace-val", namespaceAttrVal.Str())
					reasonAttrVal, ok := dp.Attributes().Get("reason")
					assert.True(t, ok)
					assert.Equal(t, "reason-val", reasonAttrVal.Str())
					statusAttrVal, ok := dp.Attributes().Get("status")
					assert.True(t, ok)
					assert.Equal(t, "status-val", statusAttrVal.Str())
					typeAttrVal, ok := dp.Attributes().Get("type")
					assert.True(t, ok)
					assert.Equal(t, "type-val", typeAttrVal.Str())
					versionAttrVal, ok := dp.Attributes().Get("version")
					assert.True(t, ok)
					assert.Equal(t, "version-val", versionAttrVal.Str())
				case "kyma.resource.status.state":
					assert.False(t, validatedMetrics["kyma.resource.status.state"], "Found a duplicate in the metrics slice: kyma.resource.status.state")
					validatedMetrics["kyma.resource.status.state"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The resource status state, metric value is 1 for the last scraped resource status state, including state as metric attribute.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					groupAttrVal, ok := dp.Attributes().Get("group")
					assert.True(t, ok)
					assert.Equal(t, "group-val", groupAttrVal.Str())
					kindAttrVal, ok := dp.Attributes().Get("kind")
					assert.True(t, ok)
					assert.Equal(t, "kind-val", kindAttrVal.Str())
					nameAttrVal, ok := dp.Attributes().Get("name")
					assert.True(t, ok)
					assert.Equal(t, "name-val", nameAttrVal.Str())
					namespaceAttrVal, ok := dp.Attributes().Get("namespace")
					assert.True(t, ok)
					assert.Equal(t, "namespace-val", namespaceAttrVal.Str())
					stateAttrVal, ok := dp.Attributes().Get("state")
					assert.True(t, ok)
					assert.Equal(t, "state-val", stateAttrVal.Str())
					versionAttrVal, ok := dp.Attributes().Get("version")
					assert.True(t, ok)
					assert.Equal(t, "version-val", versionAttrVal.Str())
				}
			}
		})
	}
}
