// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/config/configtelemetry"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("otelcol/singletonreceivercreator")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("otelcol/singletonreceivercreator")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                               metric.Meter
	ReceiverSingletonLeaderStatus       metric.Int64Gauge
	ReceiverSingletonLeaseAcquiredTotal metric.Int64Counter
	ReceiverSingletonLeaseLostTotal     metric.Int64Counter
	ReceiverSingletonLeaseSlowpathTotal metric.Int64Counter
	level                               configtelemetry.Level
}

// telemetryBuilderOption applies changes to default builder.
type telemetryBuilderOption func(*TelemetryBuilder)

// WithLevel sets the current telemetry level for the component.
func WithLevel(lvl configtelemetry.Level) telemetryBuilderOption {
	return func(builder *TelemetryBuilder) {
		builder.level = lvl
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...telemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{level: configtelemetry.LevelBasic}
	for _, op := range options {
		op(&builder)
	}
	var err, errs error
	if builder.level >= configtelemetry.LevelBasic {
		builder.meter = Meter(settings)
	} else {
		builder.meter = noop.Meter{}
	}
	builder.ReceiverSingletonLeaderStatus, err = builder.meter.Int64Gauge(
		"otelcol_receiver_singleton_leader_status",
		metric.WithDescription("A gauge of if the reporting system is the leader of the relevant lease, 0 indicates backup, and 1 indicates leader."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ReceiverSingletonLeaseAcquiredTotal, err = builder.meter.Int64Counter(
		"otelcol_receiver_singleton_lease_acquired_total",
		metric.WithDescription("The total number of successful lease acquisitions."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ReceiverSingletonLeaseLostTotal, err = builder.meter.Int64Counter(
		"otelcol_receiver_singleton_lease_lost_total",
		metric.WithDescription("The total number of lease losses."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ReceiverSingletonLeaseSlowpathTotal, err = builder.meter.Int64Counter(
		"otelcol_receiver_singleton_lease_slowpath_total",
		metric.WithDescription("The total number of slow paths exercised in renewing leader leases."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
