// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("singleton_receiver_creator")
	ScopeName = "otelcol/singletonreceivercreator"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
