// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("leaderelector")
	ScopeName = "github.com/kyma-project/opentelemetry-collector-components/extension/leaderelector"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
