apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      dummy/foo:
        interval: 1m
        lease:
          name: leaderelector/foo
      dummy/bar:
        interval: 1m
        lease:
          name: leaderelector/bar
    processors:
      batch:
    exporters:
      debug:
        verbosity: detailed
    extensions:
      leaderelector/foo:
        auth_type: kubeConfig
        lease_name: foo
        lease_namespace: default
      leaderelector/bar:
        auth_type: kubeConfig
        lease_name: bar
        lease_namespace: default

    service:
      extensions: [leaderelector/foo, leaderelector/bar]
      pipelines:
        metrics:
          receivers: [dummy/foo, dummy/bar]
    #      processors: [batch]
          exporters: [debug]
      telemetry:
        logs:
          level: debug
---
apiVersion: v1
kind: Pod
metadata:
  name: collector-1
  namespace: default
spec:
  serviceAccountName: collector
  volumes:
    - name: config
      configMap:
        name: collector-config
  containers:
    - image: europe-docker.pkg.dev/kyma-project/dev/kyma-otel-collector:PR-153
      imagePullPolicy: Always
      name: collector
      volumeMounts:
        - name: config
          mountPath: /etc/collector
      args:
        - --config=/etc/collector/config.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: collector-2
  namespace: default
spec:
  serviceAccountName: collector
  volumes:
    - name: config
      configMap:
        name: collector-config
  containers:
    - image: europe-docker.pkg.dev/kyma-project/dev/kyma-otel-collector:PR-153
      imagePullPolicy: Always
      name: collector
      volumeMounts:
        - name: config
          mountPath: /etc/collector
      args:
        - --config=/etc/collector/config.yaml