---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lease-manager
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lease-manager
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: default
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: cluster-monitor
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-monitor
# subjects:
# - kind: ServiceAccount
#   name: collector
#   namespace: default