---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      k8s_cluster:
        node_conditions_to_report: [Ready, MemoryPressure]
        allocatable_types_to_report: [cpu, memory]
    processors:
      batch:
    exporters:
      debug:
        verbosity: detailed
    
    service:
      pipelines:
        metrics:
          receivers: [k8s_cluster]
          processors: [batch]
          exporters: [debug]
      telemetry:
        logs:
          level: debug
---
apiVersion: v1
kind: Pod
metadata:
  name: collector-1
  namespace: default
spec:
  serviceAccountName: collector
  volumes:
    - name: config
      configMap:
        name: collector-config
  containers:
    - image: skhalashatsap/otel-collector:dev
      imagePullPolicy: Always
      name: collector
      volumeMounts:
        - name: config
          mountPath: /etc/collector
      args:
        - --config=/etc/collector/config.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: collector-2
  namespace: default
spec:
  serviceAccountName: collector
  volumes:
    - name: config
      configMap:
        name: collector-config
  containers:
    - image: skhalashatsap/otel-collector:dev
      imagePullPolicy: Always
      name: collector
      volumeMounts:
        - name: config
          mountPath: /etc/collector
      args:
        - --config=/etc/collector/config.yaml
