// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("leader_receiver_creator")
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
